# Generated by Django 4.1.3 on 2022-12-24 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pocket_storage", "0002_productcategory_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Отчество"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="EmployeePosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности сотрудника",
            },
        ),
        migrations.CreateModel(
            name="StorageUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("new", "новая")],
                        default="new",
                        max_length=32,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата/Время обновления записи",
                        null=True,
                        verbose_name="Обновлено",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Дата/Время создания записи",
                        verbose_name="Создано",
                    ),
                ),
                (
                    "Product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="storage_units",
                        to="pocket_storage.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "Warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="storage_units",
                        to="pocket_storage.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Единица хранения",
                "verbose_name_plural": "Единицы хранения",
            },
        ),
        migrations.CreateModel(
            name="StorageUnitOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "initial_state",
                    models.CharField(
                        choices=[("new", "новая")],
                        help_text="Состояние единицы хранения до совершения действия",
                        max_length=32,
                        verbose_name="Начальное состояние",
                    ),
                ),
                (
                    "final_state",
                    models.CharField(
                        choices=[("new", "новая")],
                        help_text="Состояние единицы хранения после совершения действия",
                        max_length=32,
                        verbose_name="Конечное состояние",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Дата/Время совершения действия",
                        verbose_name="Создано",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Сотрудник, совершивший действие",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="operations",
                        to="pocket_storage.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "storage_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="pocket_storage.storageunit",
                        verbose_name="Единица хранения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие с единицей хранения",
                "verbose_name_plural": "Действия с единицей хранения",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="pocket_storage.employeeposition",
                verbose_name="Должность",
            ),
        ),
    ]
