# Generated by Django 4.1.3 on 2023-01-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pocket_storage", "0003_employee_employeeposition_storageunit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageunit",
            name="ext_id",
            field=models.CharField(
                blank=True, max_length=24, null=True, verbose_name="Номер ячейки"
            ),
        ),
    ]
