# Generated by Django 4.1.3 on 2023-01-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pocket_storage", "0005_alter_storageunit_ext_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storageunit",
            name="ext_id",
            field=models.CharField(
                max_length=24, unique=True, verbose_name="Номер ячейки"
            ),
        ),
    ]
